name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        
      - name: Lowercase repository name
        id: lowercase
        run: echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
        
      - name: Log in to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
        with:
          context: .
          file: ./workshop/scenario_1/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repository }}/bitcoinero:latest
            ghcr.io/${{ steps.lowercase.outputs.repository }}/bitcoinero:${{ github.run_id }}
