name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - name: Lowercase repository name
        id: lowercase
        run: echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
        
      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./workshop/scenario_1/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.repository }}/bitcoinero:latest
            ghcr.io/${{ steps.lowercase.outputs.repository }}/bitcoinero:${{ github.run_id }}
