name: Publish docs and ARM templates via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs and ARM templates
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Checkout the repository
      - name: Checkout main
        uses: actions/checkout@v4

      # Step 2: Set up Bicep CLI (if needed)
      - name: Install Bicep CLI
        run: |
          az version || curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install
          az bicep version

      # Step 3: Build the Bicep files into ARM templates
      - name: Build Bicep files
        run: |
          mkdir -p docs/assets/arm-templates
          for file in $(find ./workshop/bicep -name '*.bicep'); do
            output_file=docs/assets/arm-templates/$(basename "$file" .bicep).json
            az bicep build --file "$file" --outfile "$output_file"
          done

      # Step 4: Deploy docs and ARM templates to GitHub Pages
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
