name: Build Bicep and Publish ARM Template

on:
  push:
    paths:
      - 'workshop/bicep/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Bicep CLI
    - name: Install Bicep CLI
      run: |
        az version || curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install
        az bicep version

    # Build the Bicep files into ARM templates
    - name: Build Bicep files
      run: |
        mkdir -p arm-templates
        for file in $(find ./workshop/bicep -name '*.bicep'); do
          output_file=arm-templates/$(basename "$file" .bicep).json
          az bicep build --file "$file" --outfile "$output_file"
        done

    # Upload the ARM templates as artifacts
    - name: Upload ARM templates
      uses: actions/upload-artifact@v3
      with:
        name: arm-templates
        path: arm-templates/